# Compile multi-arch PTX from src/kernels/kernels.cu (scheme B).
# Requires: CUDA Toolkit 12.x (nvcc) + VS BuildTools (cl.exe via vcvars).
param(
  [string]$CudaPath = $env:CUDA_PATH,
  [string[]]$Arches = @("61", "70", "75", "80", "86", "89", "90")
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Cu = Join-Path $Root "src\kernels\kernels.cu"
$OutDir = Join-Path $Root "ptx"

if (-not (Test-Path -LiteralPath $Cu)) {
  throw "CUDA source not found: $Cu"
}

if ([string]::IsNullOrWhiteSpace($CudaPath)) {
  $CudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8"
}
$Nvcc = Join-Path $CudaPath "bin\nvcc.exe"
if (-not (Test-Path -LiteralPath $Nvcc)) {
  throw "nvcc not found at $Nvcc (set -CudaPath or CUDA_PATH)"
}

$VcvarsCandidates = @(
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat",
  "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat",
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat",
  "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
)
$Vcvars = $VcvarsCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
if (-not $Vcvars) {
  throw "vcvars64.bat not found; install VS 2022 Build Tools (C++ desktop)"
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
Write-Host "nvcc: $Nvcc"
Write-Host "source: $Cu"
Write-Host "out: $OutDir"
Write-Host "arches: $($Arches -join ', ')"

foreach ($a in $Arches) {
  $out = Join-Path $OutDir "kernels_sm$a.ptx"
  Write-Host "==> sm_$a -> $out"
  $inner = "`"$Nvcc`" -ptx -arch=sm_$a -O3 -Wno-deprecated-gpu-targets `"$Cu`" -o `"$out`""
  cmd /c "`"$Vcvars`" >nul && $inner"
  if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $out)) {
    throw "nvcc failed for sm_$a (exit=$LASTEXITCODE)"
  }
  Write-Host "    $((Get-Item $out).Length) bytes"
}

$manifest = Join-Path $OutDir "MANIFEST.txt"
$lines = @("# Generated by scripts/compile-ptx.ps1", "# source=$Cu")
foreach ($a in $Arches) {
  $f = Join-Path $OutDir "kernels_sm$a.ptx"
  $hash = (Get-FileHash -LiteralPath $f -Algorithm SHA256).Hash
  $len = (Get-Item -LiteralPath $f).Length
  $lines += "sm$a  $len  $hash"
}
Set-Content -LiteralPath $manifest -Value $lines -Encoding utf8
Write-Host "Wrote $manifest"
Write-Host "Done."
